name: Validate CITATION.cff

on:
  pull_request:
    paths:
      - CITATION.cff
      - .github/workflows/cff-validator.yml
  push:
    branches: [main]
    paths:
      - CITATION.cff

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@v3
