name: Ruff

on:
  pull_request:
    branches: ["main"]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history to get the base branch
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }} # Checkout the PR branch
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"

      - name: Set up Python 3.13
        run: uv python pin 3.13

      - name: Run ruff linting
        run: uv run ruff check .

      - name: Run ruff formatting
        run: uv run ruff format --check .
