schema_version = "1.1"

[task]
name = "harbor/hello-mcp"
description = ""
authors = []
keywords = []

[metadata]

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
[[environment.mcp_servers]]
name = "mcp-server"
transport = "streamable-http"
url = "http://mcp-server:8000/mcp"
args = []

[verifier.env]

[environment.env]

[solution.env]
