schema_version = "1.0"

[task]
name = "widesearch/{{TASK_ID}}"
authors = [
  { name = "Ryan Wong" },
  { name = "Jiawei Wang", email = "wangjiawei.bjtu@bytedance.com" },
  { name = "Junjie Zhao" },
  { name = "Li Chen" },
  { name = "Yan Gao" },
  { name = "Long Zhang" },
  { name = "Xuan Zhou" },
  { name = "Zuo Wang" },
  { name = "Kai Xiang" },
  { name = "Ge Zhang" },
  { name = "Wenhao Huang" },
  { name = "Yang Wang" },
  { name = "Ke Wang" },
]
keywords = ["widesearch", "{{LANGUAGE}}", "{{TOPIC}}"]

[metadata]
difficulty = "hard"
category = "information-retrieval"

[verifier]
timeout_sec = 600.0
env = {}

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 600.0
docker_image = ""
cpus = 1
memory_mb = 4096
storage_mb = 10240
