schema_version = "1.0"

[task]
name = "swe-bench/swe-smith__{instance_id}"
authors = [
    { name = "John Yang", email = "johnby@stanford.edu" },
    { name = "Kilian Lieret" },
    { name = "Carlos E. Jimenez" },
    { name = "Alexander Wettig" },
    { name = "Kabir Khandpur" },
    { name = "Yanzhe Zhang" },
    { name = "Binyuan Hui" },
    { name = "Ofir Press" },
    { name = "Ludwig Schmidt" },
    { name = "Diyi Yang" },
]
keywords = ["debugging", "swe-bench", "swe-smith"]

[metadata]
benchmark = "SWE-smith"
instance_id = "{instance_id}"
repository = "{repo}"
difficulty = "{difficulty}"
category = "debugging"
source = "{source}"

[verifier]
timeout_sec = 3000.0

[agent]
timeout_sec = 3000.0
