version = "1.0"

[task]
name = "harbor/llmsr-bench"

[metadata]
author_email = "parshinshojaee@vt.edu"
author_name = "Parshin Shojaee, Kazem Meidani, Amir Barati Farimani, Chandan K. Reddy"
difficulty = "medium"
category = "scientific-equation-discovery"
tags = ["symbolic-regression", "equation-discovery"]

[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 600.0

